import image1 from "./assets/Apple Green Smith.png";
import image2 from "./assets/Avocado Hass.jpg";

export const data = [
  {
    product_image: image1,
    product_name: "Avacadose",
    brand: "Riyo Organic Markey",
    price: 60.67,
    quantity: 3,
    total: 84.3,
    status: "none",
    id: 1,
  },
  {
    product_image: image2,
    product_name: "Orange Delight",
    brand: "Nature's Best",
    price: 45.25,
    quantity: 2,
    total: 90.5,
    status: "none",
    id: 2,
  },
  {
    product_image: image1,
    product_name: "Berry Bliss",
    brand: "Fresh Harvest",
    price: 30.99,
    quantity: 4,
    total: 123.96,
    status: "none",
    id: 3,
  },
  {
    product_image: image2,
    product_name: "Grape Delight",
    brand: "Vineyard Goodness",
    price: 22.75,
    quantity: 5,
    total: 113.75,
    status: "none",
    id: 4,
  },
  {
    product_image: image1,
    product_name: "Mango Magic",
    brand: "Tropical Treats",
    price: 40.5,
    quantity: 3,
    total: 121.5,
    status: "none",
    id: 5,
  },
  {
    product_image: image2,
    product_name: "Kiwi Crunch",
    brand: "Green Goodies",
    price: 18.99,
    quantity: 6,
    total: 113.94,
    status: "none",
    id: 6,
  },
  {
    product_image: image1,
    product_name: "Peach Paradise",
    brand: "Sunshine Orchards",
    price: 28.35,
    quantity: 4,
    total: 113.4,
    status: "none",
    id: 7,
  },
  {
    product_image: image2,
    product_name: "Banana Bonanza",
    brand: "Yellow Harvest",
    price: 15.5,
    quantity: 8,
    total: 124,
    status: "none",
    id: 8,
  },
  {
    product_image: image1,
    product_name: "Blueberry Burst",
    brand: "Berry Bunch",
    price: 26.75,
    quantity: 3,
    total: 80.25,
    status: "none",
    id: 9,
  },
  {
    product_image: image2,
    product_name: "Watermelon Wonder",
    brand: "Summer Splash",
    price: 32.45,
    quantity: 2,
    total: 64.9,
    status: "none",
    id: 10,
  },
];
